### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by kcampion** [christkv/node-psutil#4]
Hello,

The installation of node-psutil has failed on my Debian VM.
# npm install psutil

[...]
/root/.node-gyp/0.10.30/deps/uv/include/uv.h:1438:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t_, uv_work_t_, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../lib/psutil_lib_osx.cc: In static member function ‘static v8::Handlev8::Value PSUtilLib::DiskPartitions(const v8::Arguments&)’:
../lib/psutil_lib_osx.cc:260:90: error: invalid conversion from ‘void (_)(uv_work_t_) {aka void (_)(uv_work_s_)}’ to ‘uv_after_work_cb {aka void (_)(uv_work_s_, int)}’ [-fpermissive]
In file included from /root/.node-gyp/0.10.30/src/node.h:61:0,
                 from ../lib/psutil_lib_osx.cc:8:
/root/.node-gyp/0.10.30/deps/uv/include/uv.h:1438:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t_, uv_work_t_, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../lib/psutil_lib_osx.cc: In static member function ‘static v8::Handlev8::Value PSUtilLib::DiskUsage(const v8::Arguments&)’:
../lib/psutil_lib_osx.cc:287:90: error: invalid conversion from ‘void (_)(uv_work_t_) {aka void (_)(uv_work_s_)}’ to ‘uv_after_work_cb {aka void (_)(uv_work_s_, int)}’ [-fpermissive]
In file included from /root/.node-gyp/0.10.30/src/node.h:61:0,
                 from ../lib/psutil_lib_osx.cc:8:
/root/.node-gyp/0.10.30/deps/uv/include/uv.h:1438:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t_, uv_work_t_, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../lib/psutil_lib_osx.cc: In static member function ‘static v8::Handlev8::Value PSUtilLib::SysConf(const v8::Arguments&)’:
../lib/psutil_lib_osx.cc:311:90: error: invalid conversion from ‘void (_)(uv_work_t_) {aka void (_)(uv_work_s_)}’ to ‘uv_after_work_cb {aka void (_)(uv_work_s_, int)}’ [-fpermissive]
In file included from /root/.node-gyp/0.10.30/src/node.h:61:0,
                 from ../lib/psutil_lib_osx.cc:8:
/root/.node-gyp/0.10.30/deps/uv/include/uv.h:1438:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t_, uv_work_t_, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
make: **\* [Release/obj.target/psutil_lib_osx/lib/psutil_lib_osx.o] Erreur 1
make: quittant le répertoire « /var/www/myproject/webapps/client/project-daemon/nodejs/src/node_modules/psutil/build »
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/myproject/webapps/client/project-daemon/nodejs/src/node_modules/psutil
gyp ERR! node -v v0.10.30
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! psutil@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the psutil@0.0.3 install script.
npm ERR! This is most likely a problem with the psutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls psutil
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "psutil"
npm ERR! cwd /var/www/myproject/webapps/client/project-daemon/nodejs/src
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/myproject/webapps/client/project-daemon/nodejs/src/npm-debug.log
npm ERR! not ok code 0

**Comment by JoaoGabrielCostaa** [comment]
same error here
